# -----------------------------------------------------------------------------
# Author Settings
# -----------------------------------------------------------------------------

author:
  name: "Vihaan Kulkarni"
  avatar: "/assets/images/profile-photo.jpg" # path to your photo
  bio: "Bridging microbiology and data science to build automated solutions for complex genomic challenges."
  location: "Mumbai, India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:vihaankulkarni29@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/vihaan-kulkarni-aa8668248/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vihaankulkarni29"