# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

title: "Vihaan Kulkarni | Computational Biologist"
description: "Personal website and portfolio of Vihaan Kulkarni, a computational biologist specializing in bioinformatics and data science."
repository: "vihaankulkarni29/vihaankulkarni29.github.io" # For an organization site, use "organization-name/repository-name"

# -----------------------------------------------------------------------------
# Author Settings
# -----------------------------------------------------------------------------

author:
  name: "Vihaan Kulkarni"
  avatar: "/assets/images/profile-photo.jpg" # path to your photo
  bio: "Bridging microbiology and data science to build automated solutions for complex genomic challenges."
  location: "Mumbai, India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:vihaankulkarni29@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/vihaan-kulkarni-aa8668248/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vihaankulkarni29"