# Site settings
# These are used to personalize your new site.
title: "Vihaan Kulkarni"
description: "Computational Biologist | Building AI-driven Bioinformatics Pipelines"
baseurl: ""
url: "https://vihaankulkarni29.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
search: true

# Build settings
markdown: kramdown
# remote_theme: mmistakes/minimal-mistakes # This line was the problem and has been removed.
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Vihaan Kulkarni"
  avatar: "/assets/images/profile-photo.jpg" # path to your photo
  bio: "Bridging microbiology and data science to build automated solutions for complex genomic challenges."
  location: "Mumbai, India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:vihaankulkarni29@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/vihaan-kulkarni-aa8668248/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vihaankulkarni29"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: # Add your twitter URL if you have one, or delete this section
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vihaankulkarni29"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/vihaan-kulkarni-aa8668248/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/